### ISSUE TITLE
Crash in p1897.cpp

### ISSUE THREAD

**Issue by cor3ntin** [facebookexperimental/libunifex#94]
The following code crashes with clang 9

https://github.com/facebookexperimental/libunifex/blob/fa377422d6af9c272df05d1f22442fdd11424adb/examples/p1897.cpp#L114

```
auto indexed_for_sender =
    indexed_for(
      std::move(just_sender),
      execution::seq,
      ranges::iota_view{3},
      [](int idx, std::vector<int>& vec, const int& i){
          vec[idx] = vec[idx] + i + idx; //!
      });
```
because `vec` is empty.
I could not determine why. My very rough understanding is that it should have size 3?

Stacktrace if helps
```
#0  0x0000000000404b54 in main::$_0::operator() (this=0x7fffffffd9e0, idx=0, vec=..., i=@0x7fffffffd9d8: 10) at ../examples/p1897.cpp:114
#1  0x0000000000404b0c in std::__1::__invoke<main::$_0&, int&, std::__1::vector<int, std::__1::allocator<int> >&, int&> (__f=..., __args=@0x7fffffffd9d8: 10, __args=@0x7fffffffd9d8: 10, __args=@0x7fffffffd9d8: 10) at /usr/lib/llvm-9/bin/../include/c++/v1/type_traits:3530
#2  0x0000000000404a9c in std::__1::invoke<main::$_0&, int&, std::__1::vector<int, std::__1::allocator<int> >&, int&> (__f=..., __args=@0x7fffffffd9d8: 10, __args=@0x7fffffffd9d8: 10, __args=@0x7fffffffd9d8: 10) at /usr/lib/llvm-9/bin/../include/c++/v1/functional:2848
#3  0x00000000004049b7 in unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type::apply_func_with_policy<std::__1::vector<int, std::__1::allocator<int> >, int> (range=..., func=..., values=@0x7fffffffd9d8: 10, values=@0x7fffffffd9d8: 10) at ../source/../include/unifex/indexed_for.hpp:57
#4  0x00000000004048a2 in unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type::set_value<std::__1::vector<int, std::__1::allocator<int> >, int>(std::__1::vector<int, std::__1::allocator<int> >&&, int&&) && (this=0x7fffffffd9e0, values=@0x7fffffffd9d8: 10, values=@0x7fffffffd9d8: 10) at ../source/../include/unifex/indexed_for.hpp:79
#5  0x0000000000404869 in unifex::_rec_cpo::_set_value_fn::_impl<false>::operator()<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int> (this=0x7fffffffd688, r=..., values=@0x7fffffffd9d8: 10, values=@0x7fffffffd9d8: 10) at ../source/../include/unifex/receiver_concepts.hpp:59
#6  0x000000000040482d in unifex::_rec_cpo::_set_value_fn::operator()<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int> (this=0x4093d8 <unifex::_rec_cpo::set_value>, r=..., values=@0x7fffffffd9d8: 10, values=@0x7fffffffd9d8: 10) at ../source/../include/unifex/receiver_concepts.hpp:47
#7  0x00000000004047eb in unifex::_just::_op<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int>::type::start() &::{lambda(std::__1::vector<int, std::__1::allocator<int> >&&, int&&)#1}::operator()(std::__1::vector<int, std::__1::allocator<int> >&&, int&&) const (this=0x7fffffffd7e0, 
    values=@0x7fffffffd9d8: 10, values=@0x7fffffffd9d8: 10) at ../source/../include/unifex/just.hpp:46
#8  0x00000000004047a7 in std::__1::__invoke_constexpr<unifex::_just::_op<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int>::type::start() &::{lambda(std::__1::vector<int, std::__1::allocator<int> >&&, int&&)#1}, std::__1::vector<int, std::__1::allocator<int> >, int> (__f=..., 
    __args=@0x7fffffffd9d8: 10, __args=@0x7fffffffd9d8: 10) at /usr/lib/llvm-9/bin/../include/c++/v1/type_traits:3536
#9  0x0000000000404743 in std::__1::__apply_tuple_impl<unifex::_just::_op<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int>::type::start() &::{lambda(std::__1::vector<int, std::__1::allocator<int> >&&, int&&)#1}, std::__1::tuple<std::__1::vector<int, std::__1::allocator<int> >, int>, 0ul, 1ul>(unifex::_just::_op<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int>::type::start() &::{lambda(std::__1::vector<int, std::__1::allocator<int> >&&, int&&)#1}&&, std::__1::tuple<std::__1::vector<int, std::__1::allocator<int> >, int>&&, std::__1::__tuple_indices<0ul, 1ul>) (__f=..., 
    __t=...) at /usr/lib/llvm-9/bin/../include/c++/v1/tuple:1376
#10 0x00000000004046b2 in std::__1::apply<unifex::_just::_op<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int>::type::start() &::{lambda(std::__1::vector<int, std::__1::allocator<int> >&&, int&&)#1}, std::__1::tuple<std::__1::vector<int, std::__1::allocator<int> >, int> >(unifex::_just::_op<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int>::type::start() &::{lambda(std::__1::vector<int, std::__1::allocator<int> >&&, int&&)#1}&&, std::__1::tuple<std::__1::vector<int, std::__1::allocator<int> >, int>&&) (__f=..., __t=...) at /usr/lib/llvm-9/bin/../include/c++/v1/tuple:1385
#11 0x00000000004045fc in unifex::_just::_op<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int>::type::start() & (this=0x7fffffffd9c0) at ../source/../include/unifex/just.hpp:44
#12 0x00000000004045c9 in unifex::_start::_fn::_impl<false>::operator()<unifex::_just::_op<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int>::type> (this=0x7fffffffd828, op=...) at ../source/../include/unifex/sender_concepts.hpp:55
#13 0x000000000040406d in unifex::_start::_fn::operator()<unifex::_just::_op<unifex::_ifor::_receiver<execution::sequenced_policy, ranges::iota_view, main::$_0, unifex::_tfx::_receiver<unifex::_sync_wait::_thread_unsafe_receiver<std::__1::vector<int, std::__1::allocator<int> >, unifex::unstoppable_token&&>::type, main::$_1>::type>::type, std::__1::vector<int, std::__1::allocator<int> >, int>::type> (this=0x4093d4 <unifex::_start::start>, op=...) at ../source/../include/unifex/sender_concepts.hpp:44
#14 0x0000000000402cdc in unifex::_sync_wait_cpo::_fn::operator()<unifex::_tfx::_sender<unifex::_ifor::_sender<unifex::_just::_sender<std::__1::vector<int, std::__1::allocator<int> >, int>::type, execution::sequenced_policy, ranges::iota_view, main::$_0>::type, main::$_1>::type, unifex::unstoppable_token, std::__1::vector<int, std::__1::allocator<int> > > (this=0x409004 <unifex::sync_wait>, sender=..., stopToken=...) at ../source/../include/unifex/sync_wait.hpp:194
```

**Comment by ericniebler** [comment]
I can build and run p1897 with clang-9 just fine. It's possible this one got fixed. What command line options are you using?

**Comment by janondrusek** [comment]
Minimum Requirements as of today:

```
GCC, 9.x and later
Clang, 10.x and later
```

We do not have CI for clang-9 enabled.
